#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

python3 - <<'PY'
from pathlib import Path
import os

keys = [
    'NEXT_PUBLIC_APP_URL',
    'BETTER_AUTH_URL',
    'BETTER_AUTH_SECRET',
    'DATABASE_URL',
    'DIRECT_URL',
    'GOOGLE_CLIENT_ID',
    'GOOGLE_CLIENT_SECRET',
    'NEXT_PUBLIC_UI_PREVIEW',
    'BETTER_AUTH_TRUSTED_ORIGINS',
    'OPENAI_API_KEY',
]


def parse_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        values[key] = value
    return values


def is_placeholder(value: str) -> bool:
    if not value:
        return True
    return any(token in value for token in ('[PROJECT-REF]', '[PASSWORD]', '[REGION]'))


values = parse_env(Path('.env.example'))
values.update(parse_env(Path('.env')))

for key in keys:
    if os.environ.get(key):
        values[key] = os.environ[key]

if is_placeholder(values.get('DATABASE_URL', '')):
    values['NEXT_PUBLIC_UI_PREVIEW'] = 'true'

values.setdefault('NEXT_PUBLIC_APP_URL', 'http://localhost:3000')
values.setdefault('BETTER_AUTH_URL', values['NEXT_PUBLIC_APP_URL'])
if not values.get('BETTER_AUTH_SECRET'):
    values['BETTER_AUTH_SECRET'] = 'dev-placeholder-secret-min-32-chars!!'

lines = [
    '# Generated by .cursor/start.sh from Cursor secrets and existing env files.',
    '',
]
for key in keys:
    if key in values:
        lines.append(f'{key}={values[key]}')

Path('.env').write_text('\n'.join(lines) + '\n')
print('Wrote .env for Cloud Agent / Chrome preview')
PY
